name: Daily Workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - feat/cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Github Release Asset from polkadot
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "paritytech/polkadot"
          file: "polkadot"
          target: "polkadot"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    
      - name: Add binaries to PATH
        run: |
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
          chmod +x polkadot

      - name: Fetch Github Release Asset from cumulus
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "paritytech/cumulus"
          file: "rococo-parachain_runtime-*.wasm"
          regex: true
          target: "./test.wasm"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move test.wasm
        run: mv test.wasm ../target/release/test.wasm

      - name: Run wasm_injector
        run: |
          cd ../target/release
          ./wasm_injector stack-overflow test.wasm
 
      - name: Checkout zombienet repository
        uses: actions/checkout@v2
        with:
          repository: paritytech/zombienet
          path: ./zombienet

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and build zombienet
        run: |
          cd ./zombienet
          npm install
          npm run build

      - name: Run zombienet
        run: |
          zombienet -p native spawn ../tests/0003-parachains-pvf-memory-allocation-bad.toml
          zombienet -p native test ../tests/0003-parachains-pvf-memory-allocation-bad.zndsl
